sudo: required
dist: trusty
language: go

go:
  - 1.12.x

services:
  - docker

branches:
  only:
    - master

cache:
  directories:
    - .terraform

env:
  global:
    - GO111MODULE=on
    - PATH=$PATH:$TRAVIS_BUILD_DIR/bin

    # AWS_CREDENTIALS_FILE
    - secure: PV7+QiwAZyw0rQQS9hRyBtU+gqrLj2p0C0r9xUcAQD9QRQKI7rHHplXMLXmVd2btiM+TEjiRwT1E2JNCtOzOlogDQBMhSfY6JFPD9nd/akOiaUpFE2QRYXN5IyumS8dC/udwqe0KZ8ckp/yxOiryUKKfxPOiqvzxxD+2CiCm7W9Hsbd33bbm1d9NPfT8k4yCRJ7ggtSsw8qDUsdMPn68tztl+7eo64lW4SV2+YfmWr1GARrmLCtSB6+LICeJgJ33BDrHX2T17nj9ChRjS6gjn98xEvYm1w74/FD5DNMTOzr0sFwsh9D6RnMxNS6c5CCDdsz8DOzCLVqmpG0CsDyqax3orTPWaIj0RZ1u/dQmlb8encsTSemVJPkQbOVu4dAQ0LLKgD1ou3rGeTYFcgkYftzdXw29CKu9NqFOqfym0iZIg6tdTiwd52mB/MLnfNUKkuVJZLf5AVP1CxwaRJyWBb0zrzasBJD4LILqCQmt6p+PenDNvjv7yBSa/+Ol1A9/g95ZtgnkqIUfre9kE5hTZiSJvXZPjVLc5jrPydYOKvbauLJewDKOzvpq0H6hRkSVUVk7sDnfZwb3z4eJfs+B7DZdmz+ZfVOWeNQ1kJejXhp93QrR4Z7VZjFKrOFb4GJ5qj2zhTYtOGfaUEP5SUji61ywC/F74SgTiX/62NuydUU=

before_install: ./ci/before_install.sh

script:
  - terraform init -input=false
  - terraform validate -check-variables=false .
  - if [[ -n "$(terraform fmt -write=false)" ]]; then echo "Some terraform files need be formatted, run 'terraform fmt' to fix"; exit 1; fi
  # - tflint bug TODO: Enable again when 0.12 support gets ready -> https://github.com/wata727/tflint#current-project-status
  - go test -v $(go list ./test/)

notifications:
  email: false
